@startuml
left to right direction

rectangle "react website" as webClient 

node "VPS" {
  rectangle phpGateway
  node ".NET Services" as dotNetServices {
    [Expense API] as ExpenseAPI
    [Income API] as IncomeAPI
    [Kobholder API] as KobholderAPI
    [IncomeSource API] as IncomeSourceAPI
    [ExpenseCategory API] as ExpenseCategoryAPI
    [IncomeCategory API] as IncomeCategoryAPI
    [Merchant API] as MerchantAPI
  }
  node "Node.js Services" as nodeServices {
    [Log Service] as logService
    [User module] as userModule
    [Import service] as importService
  
  }
}

webClient --> phpGateway : single entry point 

phpGateway --> dotNetServices : routes to
phpGateway --> nodeServices : routes to
phpGateway --> userModule : authenticate users
 

@enduml